import { getVerdictLabel } from "./helpers";
// import html2pdf from 'html2pdf.js';

// doing only as html
export const generatePDF = (analysisResult, fileName) => {
  const content = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Media Analysis Report</title>
  <style>
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
    color: #111;
    background: #fff;
    max-width: 720px;
    margin: 0 auto;
    padding: 40px 24px;
    line-height: 1.55;
  }

  h1 {
    font-size: 22px;
    margin-bottom: 4px;
    font-weight: 600;
  }

  h2 {
    font-size: 16px;
    margin: 24px 0 8px;
    font-weight: 600;
  }

  p {
    font-size: 13px;
    margin: 6px 0;
    color: #333;
  }

  .muted {
    color: #666;
    font-size: 12px;
  }

  .divider {
    border-top: 1px solid #e5e7eb;
    margin: 20px 0;
  }

  .verdict {
    font-size: 15px;
    font-weight: 600;
    margin-top: 12px;
  }

  .verdict.real {
    color: #065f46;
  }

  .verdict.fake {
    color: #991b1b;
  }

  .score {
    font-size: 14px;
    font-weight: 500;
  }

  .bar {
    height: 6px;
    background: #e5e7eb;
    margin-top: 6px;
    position: relative;
  }

  .bar-fill {
    height: 100%;
    background: #111;
    width: ${analysisResult.fake_score * 100}%;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 8px;
    font-size: 13px;
  }

  td {
    padding: 6px 0;
    vertical-align: top;
  }

  td.key {
    color: #555;
    width: 40%;
  }

  ul {
    padding-left: 16px;
    margin: 8px 0;
  }

  li {
    font-size: 13px;
    margin-bottom: 6px;
  }

  footer {
    margin-top: 40px;
    font-size: 11px;
    color: #777;
    text-align: center;
  }
.page-break {
  page-break-before: always;
}
.section {
  page-break-inside: avoid;
}
</style>
</head>
<body>
  <h1>Media Analysis Report</h1>
  <p class="muted">Deepfake detection summary</p>

  <div class="divider"></div>

  <div class="verdict ${
    analysisResult.verdict === "likely_real" ? "real" : "fake"
  }">
    Verdict: ${getVerdictLabel(analysisResult.verdict)}
  </div>
  <p class="muted">Confidence: ${analysisResult.confidence.toUpperCase()}</p>

  <h2>Manipulation Score</h2>
  <p class="score">${(analysisResult.fake_score * 100).toFixed(
    0
  )}% likelihood of manipulation</p>
  <div class="bar">
    <div class="bar-fill"></div>
  </div>

  <h2>Explanation</h2>
  <p>${analysisResult.explanation}</p>

  <h2>Detection Signals</h2>
  <ul>
    ${Object.entries(analysisResult.signals)
      .map(([k, v]) => `<li>${k.replace(/_/g, " ")}: ${v}</li>`)
      .join("")}
  </ul>

  <h2>Metadata</h2>
  <table>
    <tr>
      <td class="key">Media ID</td>
      <td>${analysisResult.media_id}</td>
    </tr>
    <tr>
      <td class="key">Media Type</td>
      <td>${analysisResult.type}</td>
    </tr>
    <tr>
      <td class="key">File Name</td>
      <td>${fileName || "N/A"}</td>
    </tr>
    <tr>
      <td class="key">Analysis Date</td>
      <td>${new Date(analysisResult.analyzed_at).toLocaleString()}</td>
    </tr>
  </table>

  <footer>
    Generated by Media Trust Analysis Dashboard<br/>
    ${new Date().toLocaleString()}
  </footer>
</body>

</html>
  `;

  const blob = new Blob([content], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `analysis-report-${analysisResult.media_id}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);

// const element = document.createElement('div');
//   element.innerHTML = content;

//   const options = {
//     margin: 10,
//     filename: `analysis-report-${analysisResult.media_id}.pdf`,
//     image: { type: 'jpeg', quality: 0.98 },
//     html2canvas: {
//       scale: 2,
//       useCORS: true,
//     },
//     jsPDF: {
//       unit: 'mm',
//       format: 'a4',
//       orientation: 'portrait',
//     },
//   };

//   html2pdf().set(options).from(element).save();
};